#! /bin/bash
git add -A
git config --global user.name "abdul0459"
git config --global user.email abdul.a0459@gmail.com
git commit -m "new things addded"
git push 'https://abdul0459:Abdul459@github.com/abdul0459/ansible.git'
