- name : Loops 
  hosts : all
  tasks :
     - name : loop
       loop :
            - google.com
            - facebook.com
            - youtube.com
       debug :
          msg : "{{item}}"