- name: Loops 
  hosts: all
  vars:
     URL: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz
     FILENAME: "{{URL.split('/') | last}}"
     DIRNAME: "{{FILENAME.split('.tar.gz')}}"
     JDBC_URL: https://github.com/citb32/project-setup/raw/master/mysql-connector-java-5.1.47.jar
     JDBC_FILENAME: "{{JDBC_URL.split('/') | last}}"
  tasks:
     - debug:
         msg: "{{DIRNAME}}"  
     - debug:
         msg: "{{JDBC_FILENAME}}"